
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bakery.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CakeCreatorView
{

    public int ID_Zamówienia { get; set; }

    public string Kształt { get; set; }

    public string Biszkopt { get; set; }

    public Nullable<int> Poziomy { get; set; }

    public string Krem { get; set; }

    public string Nadzienie { get; set; }

    public string Tynk { get; set; }

    public string Wykończenie { get; set; }

    public string Dodatki_na_ścianie_wieszchniej { get; set; }

    public string Dodatki_na_ścianie_bocznej { get; set; }

    public Nullable<decimal> Cena_za_tort { get; set; }

}

}
